
language: python

python:
# Python 2.* is no longer supported because it does not have keyword only parameters, used in a few functions and methods
  - "3.5"
  - "3.6"
# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

# command to install dependencies
install: "pip install ."

# command to run tests
script:
  - pytest
