language: python
python:
#  - "2.6"
#  - "2.7"
#  - "3.2"
#  - "3.3"
  - "3.4"
  - "3.5"
#  - "3.6"
# command to install dependencies
install: "pip install ."
# command to run tests
script:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.4 ]]; then py.test; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.5 ]]; then pytest; fi
